### ISSUE TITLE
-Inf in linear predictor

### ISSUE THREAD

**Issue by mfidino** [TravisGallo/GIV_Analysis_Repo#3]
I think that part of what is causing this is from the distance matrix D.  We convert it to km right? It still seems like we get distances that are VERY large. Our sites (at most) are 80 km from one another but we are getting distances between them that are about 3500 km which is not reasonable (in my opinion). 

This is (of course) the result of toy values to generate the cost matrix, but we cant really take the exponential of these distances without hitting 0 as we get underflow with negative exponential of these distances.

**Comment by mfidino** [comment]
Continuing with this. The population data has a range from `-0.59` to `15.69`. It's gotta be scaled if we are going to assume the types of starting values that we are using. 

I think you've already gone into logging the population data. Make sure that the raster that goes into `rcovs[[2]]` is getting scaled as well so we have wild exponentiated values in the cost function.

**Comment by TravisGallo** [comment]
The population data at the site level and the raster are both log transformed and scaled. Load the most recent workspace, then run the the MCMC_data_setup script up down to line 195 to truncated data for model runs. All that should be correct.

What do you propose for the D matrix? It maybe 80km apart, but the resistance makes them travel 3500km (in theory).

**Comment by TravisGallo** [comment]
Working with appropriate data now, removed if statements to stop ignoring error. Will report back.

**Comment by mfidino** [comment]
Sounds good to me. I'm going to check to see how well the metropolis algorithms sample against some known values to ensure they are working as expected.
